### ISSUE TITLE
Use fishfile instead of bundle?

### ISSUE THREAD

**Issue by bucaran** [fishery/fin#5]
The current location of the bundle file is `~/.config/fish/bundle` and before 1.0.0 is released I would like to decide whether we should continue to use bundle or fishfile instead. I think most people have already shared that bundle is no-good.

So here are the options:

* .fin
* .finrc
* fish_bundle
* fish_file

**Comment by herrbischoff** [comment]
A quick question: why the weird underscores? Also, `fish_bundle` is two times on the list.

**Comment by herrbischoff** [comment]
All things being equal, I like `.finrc`. Provided it's location is `~/.finrc` of course. Dotfile management FTW.

**Comment by bucaran** [comment]
@herrbischoff Haha, edited.

The reason for the weird underscores, is because fish already uses this convention for some of its files, namely `fish_history` and `fish_read_history`. We actually follow suit too and create a special fisherman/fin specific file to save the user syntax color info `fish_colors` which we use with some special prompts/themes.

**Comment by pickfire** [comment]
@herrbischoff I hate flooding `~/.`, I will donate my vote to `~/.config/fish/fishfile` or `~/.config/fish/fishers` or `~/.config/fish/fishery`.

**Comment by herrbischoff** [comment]
So, I'm casting my vote for `fish_bundle`. It feels the most fitting for me.

**Comment by watilde** [comment]
I'm doing manage my dotfiles on GitHub and this proposal would be really useful to me because at the first time I have to copy my fish files to `.config/fish/config.fish` and it annoy, like the following process:

```
## Load fish config
if [ ! -e $HOME"/.config/fish/config.fish" ]; then
  ln -s $HOME"/.fish/init.fish" $HOME"/.config/fish/config.fish"
fi

## Launch fishshell
fish
```

The reason why I used the name `.fish` is I like the concept of `.emacs.d`. Either way any name is ok to me, but let me `+1` on this idea.

**Comment by bucaran** [comment]
@watilde Why are you running fish from zsh?

**Comment by bucaran** [comment]
@fishery/all The default name of the file is still bundle, but you can set `fin_bundle` to whichever name or path you prefer and fin will write to it. This way you can have whatever you find better suited for you `~/.finrc`, `.config/fin/finfile`, etc. It's up to you.

**Comment by lordlycastle** [comment]
The reason I don't like putting the bundle/fishfile in the `~/.config/fish/` directory is because well people might think that file is part of the FISH (which it does end up being, but not from the start). Secondly, if someone were to go looking for it, they'd probably look in the `~/.config/fin/` before any other place; I know I would. Also if it's put in the `~/.config/fin/`, people _will_ quickly understand what it is just by looking at it. It lists all the functions, plugins etc. which are also in the same directory. The same logic, along with @bucaran's reasons, goes for putting it in `~/.finrc`.

As for the name, I don't think it matters much.

**Comment by bucaran** [comment]
Good points @lordlycastle, you can set `fin_bundle` to customize your location, so don't think of this as a dead end.

fin, from day one, was designed to be opinionated and pragmatic. I think your first sentence is quite true, but from a usability perspective, ~/.config/fish is a more convenient location. 

Why? Because most users probably want to commit the entire ~/.config/fish directory to git. This way you version not just stuff you can install with fin, but any custom functions / completions, as well as uvars, session history / read history, and your config.fish.
